# Title: Homelab Desired State System Configuration
# Author: Kevin harvey
# Date: 20221110
# Description: Assigns the relevant roles to systems according to their purpose.
# This playbook should be run after initial configuration and updates have been
# performed on each system.
---
- hosts: all
  become: true

  # vars_prompt:
  #   - name: docker_user
  #     prompt: "Enter User for Docker Group: "

  tasks:
    - name: Update Systems
      include_tasks: ./tasks/update.yml

    # CONFIGURE DOCKER SYSTEMS
    - name: Install Docker Role
      include_role:
        name: docker
      when: ansible_hostname == "prddock1" or ansible_hostname == "prddock2" or ansible_hostname == "prdranch1"

    - name: Add User to Docker Group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups:
          - docker
        append: yes
      when: ansible_hostname == "prddock1" or ansible_hostname == "prddock2" or ansible_hostname == "prdranch1"

    # DEPLOY DOCKER WORKLOADS
    - name: Install Jellyfin Role
      include_role:
        name: jellyfin
      when: ansible_hostname == "prddock1"

    - name: Install XMLTV Role
      include_role:
        name: zap2xml
      when: ansible_hostname == "prddock1"

    # DEPLOY MINECRAFT WORKLOADS
    - name: Install Minecraft Role
      include_role:
        name: mc_servers/minecraft
      when: ansible_hostname == "prdmc02"