---
- name: Update Homelab VMs 
  hosts: all
  become: true
  tasks:
  # Must update apt cache on Debian hosts to get up to date packages
  - name: Update APT Repos/Cache
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  # Upgrade Distros
  - name: Upgrade Debian/Ubuntu Distribution
    apt:
      upgrade: dist
      force_apt_get: yes
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Upgrade RHEL/CentOS Distribution
    dnf:
      name: "kernel"
      state: latest
    when: ansible_distribution == 'Rocky' or ansible_distribution == 'RedHat'

  # Upgrade Packages
  - name: Upgrade All Packages
    package:
      name: "*"
      state: latest

  # Reboot servers if necessary
  - name: Flag Servers for Reboot
    register: reboot_required_file_existence
    stat: path=/var/run/reboot-required get_md5=no

  - name: Reboot Servers
    reboot:
      msg: "System Reboot Required: Restarting"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    when: 
      - reboot_required_file_existence.stat.exists
      - ansible_hostname != 'ovpn'