version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: root:root
    network_mode: 'host'
    volumes:
      - jellyfinConfig:/config
      - jellyfinCache:/cache
      - /media:/media
      - /opt/xmltv/xmltvdata:/xmltv
    restart: 'unless-stopped'

volumes:
  jellyfinCache:
  jellyfinConfig: